version: '3.8'

services:
  reverse-proxy:
    image: caddy/caddy:2-alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/build/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/build/caddy/certs:/data/certs
  web:
    build:
      context: .
      dockerfile: build/web/Dockerfile
    container_name: web
    ports:
      - "8888:8888"
    restart: always
    volumes:
      - .:/web
    command: 'uvicorn rest_server:app --host 0.0.0.0 --port 8888'
  tg_bot:
    build:
      context: .
      dockerfile: ./build/tg_bot/Dockerfile
    env_file: .env
    restart: always
    volumes:
      - .:/app
    command: 'python telegram_bot.py'
volumes:
  caddy_data:
  caddy_config: